//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void CheckpointRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.writeDebuggingInfo("bundleFormatVersion");
    serializer.write<uint64_t>(bundleFormatVersion);
}

std::unique_ptr<CheckpointRecord> CheckpointRecord::deserialize(Deserializer& deserializer) {
    std::string key;
    uint64_t bundleFormatVersion = 0;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "bundleFormatVersion");
        deserializer.deserializeValue<uint64_t>(bundleFormatVersion);
    }

    return std::make_unique<CheckpointRecord>(std::move(bundleFormatVersion));
}

} // namespace storage
} // namespace lbug
