//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once


namespace lbug {
namespace storage {

struct BeginTransactionRecord final : WALRecord {

    BeginTransactionRecord() : WALRecord{WALRecordType::BEGIN_TRANSACTION_RECORD} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<BeginTransactionRecord> deserialize(
        common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
