//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#pragma once

#include <cstdint>
#include <memory>
#include <utility>
#include <vector>

#include "storage/wal/record/wal_record_base.h"

namespace lbug {
namespace storage {

struct CheckpointRecord final : WALRecord {
    uint64_t bundleFormatVersion;

    CheckpointRecord() : WALRecord{WALRecordType::CHECKPOINT_RECORD}, bundleFormatVersion{0} {}

    explicit CheckpointRecord(uint64_t bundleFormatVersion)
        : WALRecord{WALRecordType::CHECKPOINT_RECORD}, bundleFormatVersion{bundleFormatVersion} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<CheckpointRecord> deserialize(common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
