//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once


namespace lbug {
namespace storage {

struct CheckpointRecord final : WALRecord {

    CheckpointRecord() : WALRecord{WALRecordType::CHECKPOINT_RECORD} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<CheckpointRecord> deserialize(
        common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
