//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once

#include "catalog/catalog_entry/catalog_entry_type.h"
#include "common/types/types.h"

namespace lbug {
namespace storage {

struct DropCatalogEntryRecord final : WALRecord {

    common::oid_t entryID;
    catalog::CatalogEntryType entryType;

    DropCatalogEntryRecord()
        : WALRecord{WALRecordType::DROP_CATALOG_ENTRY_RECORD}, entryID{0}, entryType{} {}
    DropCatalogEntryRecord(common::oid_t entryID, catalog::CatalogEntryType entryType)
        : WALRecord{WALRecordType::DROP_CATALOG_ENTRY_RECORD}, entryID{entryID}, entryType{entryType} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<DropCatalogEntryRecord> deserialize(
        common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
