//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once

#include <string>
#include <utility>

namespace lbug {
namespace storage {

struct LoadExtensionRecord final : WALRecord {

    std::string path;

    LoadExtensionRecord()
        : WALRecord{WALRecordType::LOAD_EXTENSION_RECORD}, path{""} {}
    explicit LoadExtensionRecord(std::string path)
        : WALRecord{WALRecordType::LOAD_EXTENSION_RECORD}, path{path} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<LoadExtensionRecord> deserialize(
        common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
