//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once

#include "common/types/types.h"
#include "common/vector/value_vector.h"
#include <memory>
#include <utility>

namespace lbug {
namespace storage {

struct NodeUpdateRecord final : WALRecord {

    common::table_id_t tableID;
    common::column_id_t columnID;
    common::offset_t nodeOffset;
    common::ValueVector* propertyVector;
    std::unique_ptr<common::ValueVector> ownedPropertyVector;

    NodeUpdateRecord()
        : WALRecord{WALRecordType::NODE_UPDATE_RECORD},
          tableID{0},
          columnID{0},
          nodeOffset{0},
          propertyVector{nullptr},
          ownedPropertyVector{nullptr} {}
    NodeUpdateRecord(
        common::table_id_t tableID,
        common::column_id_t columnID,
        common::offset_t nodeOffset
    )
        : WALRecord{WALRecordType::NODE_UPDATE_RECORD}, tableID{tableID}, columnID{columnID}, nodeOffset{nodeOffset} {}
    NodeUpdateRecord(
        common::table_id_t tableID,
        common::column_id_t columnID,
        common::offset_t nodeOffset,
        common::ValueVector* propertyVector
    )
        : WALRecord{WALRecordType::NODE_UPDATE_RECORD},
          tableID{tableID},
          columnID{columnID},
          nodeOffset{nodeOffset},
          propertyVector{propertyVector},
          ownedPropertyVector{nullptr} {}
    NodeUpdateRecord(
        common::table_id_t tableID,
        common::column_id_t columnID,
        common::offset_t nodeOffset,
        std::unique_ptr<common::ValueVector> propertyVector
    )
        : WALRecord{WALRecordType::NODE_UPDATE_RECORD},
          tableID{tableID},
          columnID{columnID},
          nodeOffset{nodeOffset},
          propertyVector{nullptr},
          ownedPropertyVector{std::move(propertyVector)} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<NodeUpdateRecord> deserialize(
        common::Deserializer& deserializer,
        const main::ClientContext& clientContext);
};

} // namespace storage
} // namespace lbug
