//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once

#include "common/types/types.h"
#include "common/vector/value_vector.h"
#include <memory>
#include <utility>

namespace lbug {
namespace storage {

struct NodeDeletionRecord final : WALRecord {

    common::table_id_t tableID;
    common::offset_t nodeOffset;
    common::ValueVector* pkVector;
    std::unique_ptr<common::ValueVector> ownedPKVector;

    NodeDeletionRecord()
        : WALRecord{WALRecordType::NODE_DELETION_RECORD},
          tableID{0},
          nodeOffset{0},
          pkVector{nullptr},
          ownedPKVector{nullptr} {}
    NodeDeletionRecord(common::table_id_t tableID, common::offset_t nodeOffset)
        : WALRecord{WALRecordType::NODE_DELETION_RECORD}, tableID{tableID}, nodeOffset{nodeOffset} {}
    NodeDeletionRecord(
        common::table_id_t tableID,
        common::offset_t nodeOffset,
        common::ValueVector* pkVector
    )
        : WALRecord{WALRecordType::NODE_DELETION_RECORD},
          tableID{tableID},
          nodeOffset{nodeOffset},
          pkVector{pkVector},
          ownedPKVector{nullptr} {}
    NodeDeletionRecord(
        common::table_id_t tableID,
        common::offset_t nodeOffset,
        std::unique_ptr<common::ValueVector> pkVector
    )
        : WALRecord{WALRecordType::NODE_DELETION_RECORD},
          tableID{tableID},
          nodeOffset{nodeOffset},
          pkVector{nullptr},
          ownedPKVector{std::move(pkVector)} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<NodeDeletionRecord> deserialize(
        common::Deserializer& deserializer,
        const main::ClientContext& clientContext);
};

} // namespace storage
} // namespace lbug
