//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once

#include "common/enums/rel_direction.h"
#include "common/types/types.h"
#include "common/vector/value_vector.h"
#include <memory>
#include <utility>

namespace lbug {
namespace storage {

struct RelDetachDeleteRecord final : WALRecord {

    common::table_id_t tableID;
    common::RelDataDirection direction;
    common::ValueVector* srcNodeIDVector;
    std::unique_ptr<common::ValueVector> ownedSrcNodeIDVector;

    RelDetachDeleteRecord()
        : WALRecord{WALRecordType::REL_DETACH_DELETE_RECORD},
          tableID{0},
          direction{},
          srcNodeIDVector{nullptr},
          ownedSrcNodeIDVector{nullptr} {}
    RelDetachDeleteRecord(common::table_id_t tableID, common::RelDataDirection direction)
        : WALRecord{WALRecordType::REL_DETACH_DELETE_RECORD}, tableID{tableID}, direction{direction} {}
    RelDetachDeleteRecord(
        common::table_id_t tableID,
        common::RelDataDirection direction,
        common::ValueVector* srcNodeIDVector
    )
        : WALRecord{WALRecordType::REL_DETACH_DELETE_RECORD},
          tableID{tableID},
          direction{direction},
          srcNodeIDVector{srcNodeIDVector},
          ownedSrcNodeIDVector{nullptr} {}
    RelDetachDeleteRecord(
        common::table_id_t tableID,
        common::RelDataDirection direction,
        std::unique_ptr<common::ValueVector> srcNodeIDVector
    )
        : WALRecord{WALRecordType::REL_DETACH_DELETE_RECORD},
          tableID{tableID},
          direction{direction},
          srcNodeIDVector{nullptr},
          ownedSrcNodeIDVector{std::move(srcNodeIDVector)} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<RelDetachDeleteRecord> deserialize(
        common::Deserializer& deserializer,
        const main::ClientContext& clientContext);
};

} // namespace storage
} // namespace lbug
