//
// Auto-generated by scripts/generate_wal_records.py
// DO NOT EDIT by hand – regenerate with:
//   python3 scripts/generate_wal_records.py
//

#pragma once

#include "common/enums/table_type.h"
#include "common/types/types.h"
#include "common/vector/value_vector.h"
#include <memory>
#include <utility>
#include <vector>

namespace lbug {
namespace storage {

struct TableInsertionRecord final : WALRecord {

    common::table_id_t tableID;
    common::TableType tableType;
    common::row_idx_t numRows;

    std::vector<common::ValueVector*> vectors;
    std::vector<std::unique_ptr<common::ValueVector>> ownedVectors;

    TableInsertionRecord()
        : WALRecord{WALRecordType::TABLE_INSERTION_RECORD},
          tableID{0},
          tableType{},
          numRows{0},
          vectors{},
          ownedVectors{} {}
    TableInsertionRecord(
        common::table_id_t tableID,
        common::TableType tableType,
        common::row_idx_t numRows
    )
        : WALRecord{WALRecordType::TABLE_INSERTION_RECORD}, tableID{tableID}, tableType{tableType}, numRows{numRows} {}
    TableInsertionRecord(
        common::table_id_t tableID,
        common::TableType tableType,
        common::row_idx_t numRows,
        const std::vector<common::ValueVector*>& vectors
    )
        : WALRecord{WALRecordType::TABLE_INSERTION_RECORD},
          tableID{tableID},
          tableType{tableType},
          numRows{numRows},
          vectors{vectors},
          ownedVectors{} {}
    TableInsertionRecord(
        common::table_id_t tableID,
        common::TableType tableType,
        common::row_idx_t numRows,
        std::vector<std::unique_ptr<common::ValueVector>> vectors
    )
        : WALRecord{WALRecordType::TABLE_INSERTION_RECORD},
          tableID{tableID},
          tableType{tableType},
          numRows{numRows},
          vectors{},
          ownedVectors{std::move(vectors)} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<TableInsertionRecord> deserialize(
        common::Deserializer& deserializer,
        const main::ClientContext& clientContext);
};

} // namespace storage
} // namespace lbug
