//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "common/types/types.h"
#include "storage/wal/record/wal_record_base.h"

namespace lbug {
namespace storage {

struct UpdateSequenceNamedRecord final : WALRecord {
    common::sequence_id_t sequenceID;
    uint64_t kCount;
    std::string sequenceName;

    UpdateSequenceNamedRecord()
        : WALRecord{WALRecordType::UPDATE_SEQUENCE_NAMED_RECORD}, sequenceID{0}, kCount{0} {}

    UpdateSequenceNamedRecord(common::sequence_id_t sequenceID, uint64_t kCount,
        std::string sequenceName)
        : WALRecord{WALRecordType::UPDATE_SEQUENCE_NAMED_RECORD}, sequenceID{sequenceID},
          kCount{kCount}, sequenceName{sequenceName} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<UpdateSequenceNamedRecord> deserialize(
        common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
