name: Build Mac Precompiled Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  build-precompiled-bin-universal:
    runs-on: self-hosted-mac-x64
    steps:
      - uses: actions/checkout@v4
      
      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build universal precompiled binaries
        run: |
          make NUM_THREADS=$(sysctl -n hw.ncpu)
          make install
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          CMAKE_OSX_ARCHITECTURES: "x86_64;arm64"

      - name: Collect artifacts
        run: |
          mv install/include/lbug.h .
          mv install/include/lbug.hpp .
          mv install/lib/liblbug.dylib .
          mv install/bin/lbug .

      - name: Verify binary information
        run: |
          file -b lbug
          otool -l lbug | grep minos
          file -b liblbug.dylib
          otool -l liblbug.dylib | grep minos

      - name: Create tarball
        run: |
          tar -czvf liblbug-osx-universal.tar.gz lbug.h lbug.hpp liblbug.dylib
          tar -czvf lbug_cli-osx-universal.tar.gz lbug

      - uses: actions/upload-artifact@v4
        with:
          name: liblbug-osx-universal
          path: liblbug-osx-universal.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: lbug_cli-osx-universal
          path: lbug_cli-osx-universal.tar.gz
