name: Build Windows Precompiled Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-precompiled-bin:
    runs-on: self-hosted-windows
    if: false
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: ./scripts

      - name: Build precompiled binaries
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          make NUM_THREADS=%NUMBER_OF_PROCESSORS%
          make install

      - name: Collect artifacts
        shell: cmd
        run: |
          move install\include\lbug.h
          move install\include\lbug.hpp
          move install\bin\lbug_shared.dll
          move install\lib\lbug_shared.lib
          move install\bin\lbug_shell.exe lbug.exe

      - uses: actions/upload-artifact@v4
        with:
          name: liblbug-windows-x86_64
          path: |
            lbug.h
            lbug.hpp
            lbug_shared.dll
            lbug_shared.lib

      - uses: actions/upload-artifact@v4
        with:
          name: lbug_cli-windows-x86_64
          path: lbug.exe
